services:
  self-signer:
    image: ghcr.io/gocom/self-signer:0.2.0
    volumes:
      - ./certificates:/certificates
    environment:
      - DOMAIN
      - HOST_UID
      - HOST_GID

  reverse-proxy:
    image: nginx:mainline
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./dev/docker/image/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/certificates
    networks:
      proxy:
        aliases:
          - ${DOMAIN}
          - mailhog.${DOMAIN}
          - phpmyadmin.${DOMAIN}
    depends_on:
      self-signer:
        condition: service_completed_successfully
      nginx:
        condition: service_started
      phpmyadmin:
        condition: service_started
      mailhog:
        condition: service_started

  nginx:
    image: nginx:mainline
    volumes:
      - .:/var/www/html
      - ./dev/docker/image/nginx/conf/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - proxy
      - php
    depends_on:
      - php

  php:
    build: ./dev/docker/image/php
    volumes:
      - .:/var/www/html
    environment:
      - DOMAIN
      - PROTOCOL
      - IMAGE_HOST_URL
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_CHARSET
      - DATABASE_TABLE_PREFIX
      - MEMCACHED_HOST
      - MEMCACHED_PORT
      - ADMIN_USER_FULL_NAME
      - ADMIN_USER_EMAIL
      - ADMIN_USER_LOGIN_NAME
      - ADMIN_USER_PASSWORD
      - ADMIN_THEME
      - PUBLIC_THEME
      - TEXTPATTERN_VERSION
      - HOST_UID
      - HOST_GID
    networks:
      - php
      - mysql
    depends_on:
      - mysql
      - mailhog

  build:
    build: ./dev/docker/image/php
    volumes:
      - ./build:/var/www/html
    environment:
      - TEXTPATTERN_VERSION
      - HOST_UID
      - HOST_GID
    command: 'true'

  mysql:
    image: mysql:8.0.32-debian
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - mysql

  memcached:
    image: memcached:1.6.18-alpine
    networks:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      - PMA_HOST=${DATABASE_HOST}
      - UPLOAD_LIMIT=1G
    depends_on:
      - mysql
    networks:
      - proxy
      - mysql

  mailhog:
    image: mailhog/mailhog:v1.0.1
    networks:
      - php
      - proxy

networks:
  proxy:
  php:
  mysql:
