name: Deploy

on:
  workflow_dispatch:

jobs:
  meta:
    name: Meta
    uses: ./.github/workflows/reusable-release-meta.yml

  build:
    name: Release
    uses: ./.github/workflows/reusable-release-build.yml
    secrets: inherit
    needs: [meta]
    with:
      artifact: ${{ needs.meta.outputs.artifact }}

  deploy-development:
    name: Development
    uses: ./.github/workflows/reusable-release-deploy.yml
    secrets: inherit
    needs: [meta, build]
    with:
      environment: development
      artifact: ${{ needs.meta.outputs.artifact }}
    if: ${{ needs.meta.outputs.type == 'dev' }}

  deploy-staging:
    name: Staging
    uses: ./.github/workflows/reusable-release-deploy.yml
    secrets: inherit
    needs: [meta, build]
    with:
      environment: staging
      artifact: ${{ needs.meta.outputs.artifact }}
    if: ${{ needs.meta.outputs.type == 'release' }}

  deploy-production:
    name: Production
    uses: ./.github/workflows/reusable-release-deploy.yml
    secrets: inherit
    needs: [meta, build, deploy-staging]
    with:
      environment: production
      artifact: ${{ needs.meta.outputs.artifact }}
    if: ${{ needs.meta.outputs.type == 'release' }}
