name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Build artifact
        run: mkdir -p build/ && echo "Hello world!" > build/index

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
          if-no-files-found: warn
          include-hidden-files: true

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5

      - name: Deploy artifact
        run: ls *

  deploy-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5

      - name: Deploy artifact
        run: ls *
