name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/release-build.yml

  deploy-development:
    uses: ./.github/workflows/release-deploy.yml
    with:
      environment: development
    needs: [build]

  deploy-staging:
    uses: ./.github/workflows/release-deploy.yml
    with:
      environment: staging
    needs: [build]

  deploy-production:
    uses: ./.github/workflows/release-deploy.yml
    with:
      environment: production
    needs: [build]
