name: Release / Build

on:
  workflow_dispatch:

jobs:
  meta:
    name: Meta
    uses: ./.github/workflows/reusable-release-meta.yml

  release:
    name: Release
    uses: ./.github/workflows/reusable-release-build.yml
    needs: [meta]
    with:
      artifact: ${{ needs.meta.outputs.artifact }}
    secrets:
      slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN || '' }}
      slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID || '' }}
