name: Release / Deploy

on:
  workflow_call:
    inputs:
      run-id:
        type: number
        description: Deploy artifact from run ID
        required: false
      environment:
        type: string
        description: Environment deploy to
        required: true
  workflow_dispatch:
    inputs:
      run-id:
        type: number
        description: Deploy artifact from run ID
        required: true
      environment:
        type: environment
        description: Environment deploy to
        required: true

jobs:
  meta:
    uses: ./.github/workflows/release-meta.yml

  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [meta]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.meta.outputs.artifact }}
          path: artifact
        if: ${{ !inputs.run-id }}

      - name: Fetch artifact from previous run
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.meta.outputs.artifact }}
          path: artifact
          run-id: ${{ inputs.run-id }}
          github-token: ${{ github.token }}
        if: ${{ !!inputs.run-id }}

      - name: Deploy artifact
        run: ls -R
