name: 🚀 Release / Deploy

on:
  workflow_dispatch:
    inputs:
      run-id:
        type: number
        description: Deploy artifact from run ID
        required: true
      environment:
        type: environment
        description: Environment deploy to
        required: true

jobs:
  meta:
    name: Meta
    uses: ./.github/workflows/reusable-release-meta.yml

  release:
    name: Release
    uses: ./.github/workflows/reusable-release-deploy.yml
    needs: [meta]
    with:
      run-id: ${{ inputs.run-id }}
      environment: ${{ inputs.environment }}
      artifact: ${{ needs.meta.outputs.artifact }}
