name: Release / Build

on:
  workflow_dispatch:

jobs:
  meta:
    name: Meta
    uses: ./.github/workflows/reusable-release-meta.yml

  release:
    name: Release
    uses: ./.github/workflows/reusable-release-build.yml
    needs: [meta]
    secrets: inherit
    with:
      artifact: ${{ needs.meta.outputs.artifact }}
