name: Security scan

on:
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan Composer dependencies
        id: scan
        uses: anchore/scan-action@v6
        with:
          image: "file:composer.lock"
          fail-build: false

      - name: Print report
        run: cat ${{ steps.scan.outputs.sarif }}

      #- name: Upload report
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: ${{ steps.scan.outputs.sarif }}
